title: set up the Canon inkjet printer hardware
description: Use ij.start.canon setup to set up your Canon product. Find inkjet Canon printer and scanner support here.
google_analytics: UA-177388325-15
